# Generated by Django 5.2.1 on 2025-05-25 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("posted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("INTERNSHIP", "Internship"),
                        ],
                        max_length=50,
                    ),
                ),
                ("salary_range", models.CharField(blank=True, max_length=100)),
                ("required_skills", models.TextField()),
                ("required_experience", models.TextField()),
                ("required_education", models.TextField()),
                ("skills_keywords", models.TextField(blank=True)),
                ("experience_keywords", models.TextField(blank=True)),
                ("education_keywords", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-posted_at"],
            },
        ),
    ]
