# Generated by Django 5.2.1 on 2025-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="application_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="benefits",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="company_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="company_size",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="company_website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="founders",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="glassdoor_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="indeed_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="job_highlights",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="notice_period",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="job",
            name="work_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                    ("ONSITE", "Onsite"),
                ],
                max_length=20,
            ),
        ),
    ]
