# Generated by Django 5.2.1 on 2025-05-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("skills_match_score", models.FloatField()),
                ("experience_match_score", models.FloatField()),
                ("education_match_score", models.FloatField()),
                ("matching_skills", models.TextField(blank=True)),
                ("matching_experience", models.TextField(blank=True)),
                ("matching_education", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="resumes.resume"
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score"],
                "unique_together": {("resume", "job")},
            },
        ),
    ]
